#!/bin/sh
# File generated by ocamlbuild

cd /home/chris/Algo/Google/parsing

rm -f calc.cmi
rm -f calc.cmo
rm -f lex.ml
rm -f lexer.cmi
rm -f lexer.cmo
rm -f lexer.ml
rm -f parse_feed.cmi
rm -f parse_feed.cmo
rm -f parser.cmi
rm -f parser.cmo
rm -f parser.ml
rm -f parser.mli
# Also clean the script itself
rm -f /home/chris/Algo/Google/parsing/_build/sanitize.sh
